- build.gradle
- src/main/java/com/floney/floney/common/BaseEntity.java
- src/main/java/com/floney/floney/common/BaseException.java
- src/main/java/com/floney/floney/common/BaseResponse.java
- src/main/java/com/floney/floney/common/BaseResponseStatus.java
- src/main/java/com/floney/floney/user/controller/UserController.java
- src/main/java/com/floney/floney/user/dto/UserDTO.java
- src/main/java/com/floney/floney/user/entity/User.java
- src/main/java/com/floney/floney/user/repository/UserRepository.java
- src/main/java/com/floney/floney/user/service/UserService.java
- src/main/resources/application.properties
> [feature/1-infra] 프로젝트 초기 설정 및 user mvc 패턴 추가 

- src/main/java/com/floney/floney/FloneyApplication.java
- src/main/java/com/floney/floney/common/BaseResponseStatus.java
- src/main/java/com/floney/floney/common/config/CustomAuthenticationEntryPoint.java
- src/main/java/com/floney/floney/common/config/RedisConfig.java
- src/main/java/com/floney/floney/common/config/SecurityConfig.java
- src/main/java/com/floney/floney/common/jwt/JwtAuthenticationFilter.java
- src/main/java/com/floney/floney/common/jwt/JwtTokenProvider.java
- src/main/java/com/floney/floney/common/jwt/dto/TokenDto.java
- src/main/java/com/floney/floney/user/controller/UserController.java
- src/main/java/com/floney/floney/user/dto/UserDto.java
- src/main/java/com/floney/floney/user/dto/constant/Provider.java
- src/main/java/com/floney/floney/user/dto/constant/Role.java
- src/main/java/com/floney/floney/user/dto/request/UserLoginRequestDto.java
- src/main/java/com/floney/floney/user/dto/request/UserSignupRequestDto.java
- src/main/java/com/floney/floney/user/dto/security/UserPrincipal.java
- src/main/java/com/floney/floney/user/entity/AuditingFields.java
- src/main/java/com/floney/floney/user/entity/User.java
- src/main/java/com/floney/floney/user/repository/UserRepository.java
- src/main/java/com/floney/floney/user/service/UserDetailService.java
- src/main/java/com/floney/floney/user/service/UserService.java
> [feature/3-login] user api 구현

- src/main/java/com/floney/floney/common/exception/CodeNotSameException.java
- src/main/java/com/floney/floney/common/exception/EmailNotFoundException.java
- src/main/java/com/floney/floney/common/exception/ErrorControllerAdvice.java
- src/main/java/com/floney/floney/common/exception/ErrorType.java
- src/main/java/com/floney/floney/common/token/RedisProvider.java
- src/main/java/com/floney/floney/user/controller/UserController.java
- src/main/java/com/floney/floney/user/dto/request/EmailAuthenticationRequest.java
- src/main/java/com/floney/floney/user/dto/request/LoginRequest.java
- src/main/java/com/floney/floney/user/dto/request/SignupRequest.java
- src/main/java/com/floney/floney/user/service/UserService.java
- src/test/java/com/floney/floney/User/controller/UserControllerTest.java
- src/test/java/com/floney/floney/User/service/UserServiceTest.java
> 24 feature 이메일 인증 추가 구현

- src/main/java/com/floney/floney/user/dto/request/LoginRequest.java
- src/test/java/com/floney/floney/User/TestUserDetailService.java
- src/test/java/com/floney/floney/User/controller/UserControllerTest.java
- src/test/java/com/floney/floney/User/service/UserServiceTest.java
- src/test/java/com/floney/floney/config/TestConfig.java
> 16 fix usercontrollertest 오류 수정

- src/main/java/com/floney/floney/book/controller/BookController.java
- src/main/java/com/floney/floney/book/entity/Book.java
- src/main/java/com/floney/floney/book/entity/BookUser.java
- src/main/java/com/floney/floney/book/repository/BookUserCustomRepository.java
- src/main/java/com/floney/floney/book/repository/BookUserRepository.java
- src/main/java/com/floney/floney/book/repository/BookUserRepositoryImpl.java
- src/main/java/com/floney/floney/book/service/BookService.java
- src/main/java/com/floney/floney/book/service/BookServiceImpl.java
- src/main/java/com/floney/floney/common/exception/ErrorControllerAdvice.java
- src/main/java/com/floney/floney/common/exception/ErrorType.java
- src/main/java/com/floney/floney/common/exception/NoAuthorityException.java
- src/test/java/com/floney/floney/book/BookServiceTest.java
- src/test/java/com/floney/floney/book/BookTest.java
- src/test/java/com/floney/floney/book/BookUserRepositoryTest.java
> 35 feature 가계부 편집 및 삭제

- src/main/java/com/floney/floney/book/entity/Book.java
- src/main/java/com/floney/floney/book/service/BookServiceImpl.java
- src/test/java/com/floney/floney/book/BookLineFixture.java
- src/test/java/com/floney/floney/book/BookServiceTest.java
> #33 fix : column 오류 수정

- src/main/java/com/floney/floney/book/controller/BookController.java
- src/main/java/com/floney/floney/common/config/SecurityConfig.java
- src/main/java/com/floney/floney/user/controller/UserController.java
- src/main/java/com/floney/floney/user/dto/request/EmailAuthenticationRequest.java
- src/main/java/com/floney/floney/user/service/UserService.java
> #23 refactor: 인증된 유저 정보 @AuthenticationPrincipal로 가져오도록 리팩토링

- build.gradle
- src/main/java/com/floney/floney/book/controller/BookController.java
- src/main/java/com/floney/floney/book/dto/BookNameChangeRequest.java
- src/main/java/com/floney/floney/book/dto/BookResponse.java
- src/main/java/com/floney/floney/book/dto/CodeJoinRequest.java
- src/main/java/com/floney/floney/book/entity/Book.java
- src/main/java/com/floney/floney/book/entity/BookLine.java
- src/main/java/com/floney/floney/book/entity/Category.java
- src/main/java/com/floney/floney/book/service/BookService.java
- src/main/java/com/floney/floney/book/service/BookServiceImpl.java
- src/test/java/com/floney/floney/book/BookFixture.java
- src/test/java/com/floney/floney/book/BookServiceTest.java
#36
저 가장 최근 커밋인 가계부에 참여 코드를 이용하여 참여한다 PARAM -> BODY 는 분명 로컬에서 한번 커밋 했는데, 왜 3번이나 나오는지 모르겠네요.....
> 36 refactor requestparam body로 수정

- src/main/java/com/floney/floney/common/CustomAuthenticationEntryPoint.java
- src/main/java/com/floney/floney/common/MailProvider.java
- src/main/java/com/floney/floney/common/config/SecurityConfig.java
- src/main/java/com/floney/floney/common/exception/EmailNotValidException.java
- src/main/java/com/floney/floney/common/exception/ErrorControllerAdvice.java
- src/main/java/com/floney/floney/common/exception/ErrorType.java
- src/main/java/com/floney/floney/common/exception/OAuthResponseException.java
- src/main/java/com/floney/floney/common/token/JwtAuthenticationFilter.java
- src/main/java/com/floney/floney/common/token/JwtProvider.java
- src/main/java/com/floney/floney/user/client/ClientProxy.java
- src/main/java/com/floney/floney/user/client/GoogleClient.java
- src/main/java/com/floney/floney/user/client/KakaoClient.java
- src/main/java/com/floney/floney/user/controller/UserController.java
- src/main/java/com/floney/floney/user/dto/request/EmailAuthenticationRequest.java
- src/main/java/com/floney/floney/user/dto/request/LoginRequest.java
- src/main/java/com/floney/floney/user/dto/request/SignupRequest.java
- src/main/java/com/floney/floney/user/dto/response/GoogleUserResponse.java
- src/main/java/com/floney/floney/user/dto/response/KakaoUserResponse.java
- src/main/java/com/floney/floney/user/dto/response/MyPageResponse.java
- src/main/java/com/floney/floney/user/dto/response/UserResponse.java
- src/main/java/com/floney/floney/user/dto/security/UserDetail.java
- src/main/java/com/floney/floney/user/service/CustomUserDetailService.java
- src/main/java/com/floney/floney/user/service/OAuthUserService.java
- src/main/java/com/floney/floney/user/service/UserService.java
- src/test/java/com/floney/floney/User/TestUserDetailService.java
- src/test/java/com/floney/floney/User/controller/UserControllerTest.java
- src/test/java/com/floney/floney/User/service/UserServiceTest.java
- src/test/java/com/floney/floney/config/WithMockCustomUserSecurityContextFactory.java
#17
- 실제 작동하는 지는 프론트랑 같이 확인이 필요함
> 17 fix 간편 로그인 방식 수정

- src/main/java/com/floney/floney/book/dto/BookLineExpense.java
- src/main/java/com/floney/floney/book/dto/BookLineResponse.java
- src/main/java/com/floney/floney/book/dto/CategoryResponse.java
- src/main/java/com/floney/floney/book/dto/CodeJoinRequest.java
- src/main/java/com/floney/floney/book/dto/DayLineInfo.java
- src/main/java/com/floney/floney/book/dto/DayLines.java
- src/main/java/com/floney/floney/book/dto/MonthLinesResponse.java
- src/main/java/com/floney/floney/book/dto/TotalDayLinesResponse.java
- src/main/java/com/floney/floney/book/dto/TotalExpense.java
- src/main/java/com/floney/floney/book/repository/BookUserCustomRepository.java
- src/main/java/com/floney/floney/book/repository/BookUserRepositoryImpl.java
- src/main/java/com/floney/floney/book/service/BookLineServiceImpl.java
- src/main/java/com/floney/floney/book/service/BookServiceImpl.java
- src/main/java/com/floney/floney/book/service/CategoryServiceImpl.java
- src/main/java/com/floney/floney/common/exception/ErrorControllerAdvice.java
- src/main/java/com/floney/floney/common/exception/ErrorType.java
- src/main/java/com/floney/floney/common/exception/NotFoundBookUserException.java
- src/test/java/com/floney/floney/book/BookServiceTest.java
- src/test/java/com/floney/floney/book/BookUserRepositoryTest.java
- src/test/java/com/floney/floney/book/CodeFactoryTest.java
> 46 fix 자잘한 에러

- src/main/java/com/floney/floney/book/entity/BookUser.java
- src/main/java/com/floney/floney/book/repository/BookUserRepository.java
- src/main/java/com/floney/floney/common/config/SecurityConfig.java
- src/main/java/com/floney/floney/user/service/UserService.java
> #37 feat : 프로필 사진 수정 시 bookUser 정보 업데이트

- src/main/java/com/floney/floney/book/controller/BookController.java
- src/main/java/com/floney/floney/book/dto/OurBookInfo.java
- src/main/java/com/floney/floney/book/dto/OurBookUser.java
- src/main/java/com/floney/floney/book/repository/BookUserCustomRepository.java
- src/main/java/com/floney/floney/book/repository/BookUserRepositoryImpl.java
- src/main/java/com/floney/floney/book/service/BookService.java
- src/main/java/com/floney/floney/book/service/BookServiceImpl.java
- src/main/java/com/floney/floney/book/util/DateFactory.java
- src/test/java/com/floney/floney/book/BookFixture.java
- src/test/java/com/floney/floney/book/BookUserRepositoryTest.java
- src/test/java/com/floney/floney/book/OurBookUserTest.java
- src/test/java/com/floney/floney/config/UserFixture.java
> 52 feature 가계부 설정

- src/main/java/com/floney/floney/book/dto/CreateBookRequest.java
- src/main/java/com/floney/floney/book/dto/OurBookInfo.java
- src/main/java/com/floney/floney/book/dto/OurBookUser.java
- src/main/java/com/floney/floney/book/entity/Book.java
- src/main/java/com/floney/floney/book/service/BookServiceImpl.java
- src/test/java/com/floney/floney/book/BookFixture.java
- src/test/java/com/floney/floney/book/BookTest.java
#55
- Book 의 providerEmail -> owner 로 수정
> 55 refactor 가계부 provider 필드 owner로 수정

- src/main/java/com/floney/floney/common/exception/ErrorControllerAdvice.java
- src/main/java/com/floney/floney/common/exception/ErrorType.java
- src/main/java/com/floney/floney/common/exception/OAuthTokenNotValidException.java
- src/main/java/com/floney/floney/user/client/ClientProxy.java
- src/main/java/com/floney/floney/user/client/GoogleClient.java
- src/main/java/com/floney/floney/user/client/KakaoClient.java
- src/main/java/com/floney/floney/user/dto/request/SignupRequest.java
- src/main/java/com/floney/floney/user/entity/User.java
- src/main/java/com/floney/floney/user/repository/UserRepository.java
- src/main/java/com/floney/floney/user/service/GoogleUserService.java
- src/main/java/com/floney/floney/user/service/KakaoUserService.java
#59
- User의 provider_id의 타입이 Long -> String으로 변경
- 이슈에 적힌 모든 사항을 구현하진 않음 (눈수술 후 구현 예정, 프론트와의 테스트 위해 우선 올립니다)
> 59 test 간편 로그인 테스트 코드 추가

- src/main/java/com/floney/floney/book/entity/Book.java
- src/main/java/com/floney/floney/book/entity/BookUser.java
- src/main/java/com/floney/floney/book/repository/BookLineRepositoryImpl.java
- src/main/java/com/floney/floney/book/repository/BookRepository.java
- src/main/java/com/floney/floney/book/repository/BookUserRepository.java
- src/main/java/com/floney/floney/book/repository/BookUserRepositoryImpl.java
- src/main/java/com/floney/floney/book/service/BookLineServiceImpl.java
- src/main/java/com/floney/floney/book/service/BookServiceImpl.java
- src/main/java/com/floney/floney/book/service/CategoryServiceImpl.java
- src/main/java/com/floney/floney/common/BaseEntity.java
- src/main/java/com/floney/floney/common/constant/Status.java
- src/main/java/com/floney/floney/user/dto/response/UserResponse.java
- src/main/java/com/floney/floney/user/entity/User.java
- src/main/java/com/floney/floney/user/repository/UserRepository.java
- src/main/java/com/floney/floney/user/service/UserService.java
- src/test/java/com/floney/floney/User/UserRepositoryTest.java
- src/test/java/com/floney/floney/User/service/UserServiceTest.java
- src/test/java/com/floney/floney/book/BookLineRepositoryTest.java
- src/test/java/com/floney/floney/book/BookServiceTest.java
- src/test/java/com/floney/floney/book/BookUserRepositoryTest.java
- src/test/java/com/floney/floney/book/CategoryServiceTest.java
- src/test/java/com/floney/floney/config/WithMockCustomUserSecurityContextFactory.java
#61
- Status 를 Varchar(20)으로 변경
- Status default는 ACTIVE
- delete()메서드를 공통적으로 Base Entity에서 관리하도록 함
> 61 refactor status enum관리하기

- src/main/java/com/floney/floney/book/controller/BookController.java
- src/main/java/com/floney/floney/book/dto/BookResponse.java
- src/main/java/com/floney/floney/book/dto/CreateBookRequest.java
- src/main/java/com/floney/floney/book/dto/OurBookInfo.java
- src/main/java/com/floney/floney/book/dto/SeeProfileRequest.java
- src/main/java/com/floney/floney/book/dto/TotalDayLinesResponse.java
- src/main/java/com/floney/floney/book/dto/UpdateAssetRequest.java
- src/main/java/com/floney/floney/book/dto/UpdateBookImgRequest.java
- src/main/java/com/floney/floney/book/dto/UpdateBudgetRequest.java
- src/main/java/com/floney/floney/book/entity/Book.java
- src/main/java/com/floney/floney/book/repository/BookLineCustomRepository.java
- src/main/java/com/floney/floney/book/repository/BookLineRepositoryImpl.java
- src/main/java/com/floney/floney/book/repository/BookUserRepositoryImpl.java
- src/main/java/com/floney/floney/book/service/BookLineService.java
- src/main/java/com/floney/floney/book/service/BookLineServiceImpl.java
- src/main/java/com/floney/floney/book/service/BookService.java
- src/main/java/com/floney/floney/book/service/BookServiceImpl.java
- src/test/java/com/floney/floney/book/BookFixture.java
- src/test/java/com/floney/floney/book/BookTest.java
- src/test/java/com/floney/floney/config/TestConfig.java
- src/test/java/com/floney/floney/config/UserFixture.java
#57
- 가계부 내의 profile_img 필드 -> book_img 변경
> 57 feature 가계부 설정 세부 기능 구현

- src/main/java/com/floney/floney/book/repository/BookUserRepository.java
- src/main/java/com/floney/floney/user/service/UserService.java
> #67 feat : user 삭제 시 나의 bookuser 계정 전체 삭제

- src/main/java/com/floney/floney/book/controller/CategoryController.java
- src/main/java/com/floney/floney/book/repository/category/CategoryCustomRepository.java
- src/main/java/com/floney/floney/book/repository/category/CategoryRepository.java
- src/main/java/com/floney/floney/book/repository/category/CategoryRepositoryImpl.java
- src/main/java/com/floney/floney/book/service/CategoryService.java
- src/main/java/com/floney/floney/book/service/CategoryServiceImpl.java
- src/test/java/com/floney/floney/book/CategoryRepositoryTest.java
> #69 feat : 커스텀 카테고리 삭제하기

- src/main/java/com/floney/floney/book/controller/BookController.java
- src/main/java/com/floney/floney/book/dto/CheckBookValidResponse.java
- src/main/java/com/floney/floney/book/entity/Book.java
- src/main/java/com/floney/floney/book/repository/BookUserCustomRepository.java
- src/main/java/com/floney/floney/book/repository/BookUserRepositoryImpl.java
- src/main/java/com/floney/floney/book/repository/category/CategoryRepositoryImpl.java
- src/main/java/com/floney/floney/book/service/BookService.java
- src/main/java/com/floney/floney/book/service/BookServiceImpl.java
- src/test/java/com/floney/floney/book/BookUserRepositoryTest.java
- src/test/java/com/floney/floney/book/CategoryRepositoryTest.java
- src/test/java/com/floney/floney/book/CheckValidResponseTest.java
> #71 feat : 유저에 대한 가계부 존재 여부 확인하기

- src/main/java/com/floney/floney/book/entity/RootCategory.java
- src/main/java/com/floney/floney/book/repository/category/CategoryRepositoryImpl.java
- src/test/java/com/floney/floney/book/CategoryFixture.java
- src/test/java/com/floney/floney/book/CategoryRepositoryTest.java
- src/test/java/com/floney/floney/book/CategoryServiceTest.java
#76 
- 루트 카테고리 DTYPE을 RootCategory로 변경 
- 내용
> #76 fix : 루트 카테고리 DTYPE 변경

- build.gradle
- src/main/java/com/floney/floney/FloneyApplication.java
- src/main/java/com/floney/floney/JobConfiguration.java
- src/main/java/com/floney/floney/book/dto/CarryOverInfo.java
- src/main/java/com/floney/floney/book/dto/CategoryCreator.java
- src/main/java/com/floney/floney/book/entity/CarryOver.java
- src/main/java/com/floney/floney/book/util/CategoryFactory.java
- src/test/java/com/floney/floney/book/CarryOverTest.java
#66
- 아직 AWS DB는 변경하지 않았습니다 
- batch에 필요한 Table 10개 생성 예정
- 너무 오래 걸렸습니다..파악하고..예제 돌려보고 그러느냐고..
- 아직 스케줄러(매월 1일 작동하기)는 구현 하지 않았습니다 -> 그것도 Quartz라는 기능을 배워야 하더라고요
- merge할 때 너무 충돌 날까봐, 일단 1차 PR올리겠습니다
- 시간에 쫓기다 보니, 저도 애매하게 아는 부분이 몇가지 있어 차차 블로그 포스팅을 하며 정확히 이해해보겠습니다.
> 66 feature 이월설정

- src/main/java/com/floney/floney/book/dto/OurBookInfo.java
> #85 refactor : 가계부 설정 조회필드 추가

- src/main/java/com/floney/floney/book/controller/BookController.java
- src/main/java/com/floney/floney/book/repository/BookLineRepositoryImpl.java
> 88 refactor 내역조회시 이미지 변경 수정

- src/main/java/com/floney/floney/book/controller/BookController.java
- src/main/java/com/floney/floney/book/dto/CategoryInfo.java
- src/main/java/com/floney/floney/book/dto/CreateCategoryResponse.java
- src/main/java/com/floney/floney/book/repository/category/CategoryCustomRepository.java
- src/main/java/com/floney/floney/book/repository/category/CategoryRepositoryImpl.java
- src/main/java/com/floney/floney/book/service/CategoryService.java
- src/main/java/com/floney/floney/book/service/CategoryServiceImpl.java
- src/test/java/com/floney/floney/book/CategoryFixture.java
> 91 refactor 커스텀 카테고리 마킹 조회

- src/main/java/com/floney/floney/book/service/BookServiceImpl.java
- src/main/java/com/floney/floney/common/config/BatchConfiguration.java
- src/main/java/com/floney/floney/common/config/JobConfiguration.java
- src/main/java/com/floney/floney/common/config/Scheduler.java
> 93 feature 이월스케줄링

- src/main/java/com/floney/floney/book/controller/BookController.java
- src/main/java/com/floney/floney/book/repository/category/CategoryCustomRepository.java
- src/main/java/com/floney/floney/book/repository/category/CategoryRepositoryImpl.java
- src/main/java/com/floney/floney/book/service/CategoryService.java
> #99 fix : 머지 충돌 해결

- src/main/java/com/floney/floney/book/controller/BookController.java
- src/main/java/com/floney/floney/book/dto/process/DayLine.java
- src/main/java/com/floney/floney/book/dto/process/DayLineInfo.java
- src/main/java/com/floney/floney/book/dto/process/DayLines.java
- src/main/java/com/floney/floney/book/dto/request/AllOutcomesRequest.java
- src/main/java/com/floney/floney/book/repository/BookLineRepositoryImpl.java
- src/main/java/com/floney/floney/book/repository/BookUserRepositoryImpl.java
- src/main/java/com/floney/floney/book/service/BookLineService.java
- src/main/java/com/floney/floney/book/service/BookLineServiceImpl.java
- src/test/java/com/floney/floney/book/BookUserRepositoryTest.java
#102
금주 미팅을 통해, 현재 로그인한 사용자는 자동 포함이 아닌 선택으로 변경이 되었습니다!
> 102 refactor 유저를 포함하게 내역 api 수정

- src/main/java/com/floney/floney/book/controller/BookController.java
- src/main/java/com/floney/floney/book/dto/response/InviteCodeResponse.java
- src/main/java/com/floney/floney/book/service/BookService.java
- src/main/java/com/floney/floney/book/service/BookServiceImpl.java
> #104 feat : 초대코드 조회 API

- src/main/java/com/floney/floney/book/controller/BookController.java
- src/main/java/com/floney/floney/book/dto/request/BookUserOutRequest.java
- src/main/java/com/floney/floney/book/repository/BookLineCustomRepository.java
- src/main/java/com/floney/floney/book/repository/BookLineRepository.java
- src/main/java/com/floney/floney/book/repository/BookLineRepositoryImpl.java
- src/main/java/com/floney/floney/book/repository/BookUserRepositoryImpl.java
- src/main/java/com/floney/floney/book/service/BookService.java
- src/main/java/com/floney/floney/book/service/BookServiceImpl.java
> 106 feature 가계부 나가기

- src/main/java/com/floney/floney/book/controller/BookController.java
- src/main/java/com/floney/floney/book/dto/process/DayLine.java
- src/main/java/com/floney/floney/book/dto/process/DayLineInfo.java
- src/main/java/com/floney/floney/book/dto/process/DayLines.java
- src/main/java/com/floney/floney/book/dto/request/CreateLineRequest.java
- src/main/java/com/floney/floney/book/repository/BookLineRepositoryImpl.java
#109
- profile 이미지 없으면 user_default로 default 설정
> 109 refactor 지출내역응답값변경

- src/main/java/com/floney/floney/book/controller/BookController.java
- src/main/java/com/floney/floney/common/exception/common/ErrorType.java
- src/main/java/com/floney/floney/common/exception/user/PasswordSameException.java
- src/main/java/com/floney/floney/user/dto/response/MyPageResponse.java
- src/main/java/com/floney/floney/user/service/UserService.java
- src/test/java/com/floney/floney/User/service/UserServiceTest.java
> [fix] 유저 api 오류 수정 및 기능 변경

- src/main/java/com/floney/floney/book/controller/BookController.java
- src/main/java/com/floney/floney/book/dto/response/BookUserResponse.java
- src/main/java/com/floney/floney/book/service/BookService.java
- src/main/java/com/floney/floney/book/service/BookServiceImpl.java
> 115 fix 가계부의 유저 목록 조회 api 수정

- src/main/java/com/floney/floney/book/controller/BookController.java
- src/main/java/com/floney/floney/book/entity/BookAnalyze.java
- src/main/java/com/floney/floney/book/repository/BookRepository.java
- src/main/java/com/floney/floney/book/service/BookService.java
- src/main/java/com/floney/floney/book/service/BookServiceImpl.java
#126
- 컨플릭트 해결은 인텔리제이에서...!!!!!!!!!! 🫣
> 126 fix 컨플릭트 해결로 인한 빌드 에러 해결

- .github/CODEOWNERS
- .github/workflows/gradle-build.yml
- .github/workflows/gradle.yml
- build.gradle
- src/test/java/com/floney/floney/User/controller/UserControllerTest.java
- src/test/java/com/floney/floney/User/repository/UserRepositoryTest.java
- src/test/resources/application.yaml
> 146 refactor: 테스트 설정 분리

- src/main/java/com/floney/floney/book/controller/BookController.java
- src/main/java/com/floney/floney/book/service/BookService.java
- src/main/java/com/floney/floney/book/service/BookServiceImpl.java
> #152 feat : 화폐 단위 조회 API

- .gitignore
- src/main/resources/logback-spring.xml
> #156 chore : 로그백 설정 파일

- .github/workflows/gradle.yml
> 158 CD 워크플로우 코드 수정

- src/main/java/com/floney/floney/book/controller/BookController.java
- src/main/java/com/floney/floney/book/dto/process/DayLineByDayView.java
- src/main/java/com/floney/floney/book/dto/process/DayLineInfo.java
- src/main/java/com/floney/floney/book/dto/process/DayLines.java
- src/main/java/com/floney/floney/book/dto/response/BookInfoResponse.java
- src/main/java/com/floney/floney/book/repository/BookLineRepositoryImpl.java
- src/main/java/com/floney/floney/book/repository/BookUserCustomRepository.java
- src/main/java/com/floney/floney/book/repository/BookUserRepositoryImpl.java
- src/main/java/com/floney/floney/book/service/BookService.java
- src/main/java/com/floney/floney/book/service/BookServiceImpl.java
- src/main/java/com/floney/floney/common/DeleteService.java
- src/main/java/com/floney/floney/common/exception/book/AlreadyJoinException.java
- src/main/java/com/floney/floney/common/exception/common/ErrorControllerAdvice.java
- src/main/java/com/floney/floney/common/exception/common/ErrorType.java
- src/main/java/com/floney/floney/user/dto/constant/SubscribeStatus.java
- src/main/java/com/floney/floney/user/entity/User.java
- src/main/java/com/floney/floney/user/service/SubscribeService.java
- src/test/java/com/floney/floney/book/BookServiceTest.java
- src/test/java/com/floney/floney/book/BookUserRepositoryTest.java
> 160 refactor fe 추가 요청사항

- src/main/java/com/floney/floney/book/controller/BookController.java
- src/main/java/com/floney/floney/book/dto/process/DayLines.java
- src/main/java/com/floney/floney/book/dto/process/OurBookInfo.java
- src/main/java/com/floney/floney/book/dto/response/MonthLinesResponse.java
- src/main/java/com/floney/floney/book/repository/BookLineCustomRepository.java
- src/main/java/com/floney/floney/book/repository/BookLineRepository.java
- src/main/java/com/floney/floney/book/repository/BookLineRepositoryImpl.java
- src/main/java/com/floney/floney/book/repository/BookUserRepository.java
- src/main/java/com/floney/floney/book/repository/BookUserRepositoryImpl.java
- src/main/java/com/floney/floney/book/service/BookService.java
- src/main/java/com/floney/floney/book/service/BookServiceImpl.java
- src/main/java/com/floney/floney/settlement/service/SettlementService.java
- src/main/java/com/floney/floney/user/entity/User.java
- src/main/java/com/floney/floney/user/service/UserService.java
#151
- 회원 탈퇴시, 즉시 개인정보 데이터가 삭제 되어야함. 따라서, email이 null로 바뀔 수 있도록 updatable 제거
- 개인정보 필드 NOT NULL 조항 제거 = null값으로 바꾸기 위함
- 내용
> 151 feature 회원 탈퇴시 가계부 정보 삭제

- src/main/java/com/floney/floney/book/controller/BookController.java
- src/main/java/com/floney/floney/book/entity/Book.java
- src/main/java/com/floney/floney/book/repository/BookUserCustomRepository.java
- src/main/java/com/floney/floney/book/repository/BookUserRepositoryImpl.java
- src/main/java/com/floney/floney/book/service/BookService.java
- src/main/java/com/floney/floney/book/service/BookServiceImpl.java
- src/main/java/com/floney/floney/common/constant/Subscribe.java
- src/main/java/com/floney/floney/common/dto/DelegateResponse.java
- src/main/java/com/floney/floney/common/exception/common/ErrorControllerAdvice.java
- src/main/java/com/floney/floney/common/exception/common/ErrorType.java
- src/main/java/com/floney/floney/common/exception/settlement/OutcomeUserNotFoundException.java
- src/main/java/com/floney/floney/common/exception/settlement/SettlementNotFoundException.java
- src/main/java/com/floney/floney/common/exception/user/CodeNotSameException.java
- src/main/java/com/floney/floney/common/exception/user/NotFoundSubscribeException.java
- src/main/java/com/floney/floney/user/controller/UserController.java
- src/main/java/com/floney/floney/user/dto/request/SubscribeRequest.java
- src/main/java/com/floney/floney/user/repository/SubscribeRepository.java
- src/main/java/com/floney/floney/user/service/SubscribeService.java
- src/main/java/com/floney/floney/user/service/UserService.java
- src/test/java/com/floney/floney/User/SubscribeServiceTest.java
- src/test/java/com/floney/floney/User/service/SubscribeServiceTest.java
- src/test/java/com/floney/floney/User/service/UserServiceTest.java
- src/test/java/com/floney/floney/book/BookFixture.java
- src/test/java/com/floney/floney/book/BookServiceTest.java
- src/test/java/com/floney/floney/config/UserFixture.java
#163
- bookStatus 필드 추가(구독 해지에 의한 가계부 비활성화/ 활성화 여부)
- 내용
> 163 feature 구독 관련 기능

- src/main/java/com/floney/floney/book/dto/process/CarryOverFactory.java
- src/main/java/com/floney/floney/book/dto/process/CarryOverInfo.java
- src/main/java/com/floney/floney/book/entity/CarryOver.java
- src/main/java/com/floney/floney/book/repository/CarryOverRepository.java
- src/main/java/com/floney/floney/book/service/BookLineServiceImpl.java
- src/main/java/com/floney/floney/book/util/DateFactory.java
#162
<pre>
CREATE TABLE `carry_over` (
`id` bigint NOT NULL AUTO_INCREMENT,
`created_at` datetime(6) DEFAULT NULL,
`status` varchar(255) DEFAULT NULL,
`updated_at` datetime(6) DEFAULT NULL,
`date` date DEFAULT NULL,
`money` bigint NOT NULL,
`book_id` bigint DEFAULT NULL,
PRIMARY KEY (`id`),
KEY `FKk6ik5p5rhx0oluc38k4fi3tok` (`book_id`),
CONSTRAINT `FKk6ik5p5rhx0oluc38k4fi3tok` FOREIGN KEY (`book_id`) REFERENCES `book` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
</pre>
- 내용
> 162 feature 이월 설정 재구현

- src/main/java/com/floney/floney/book/controller/BookController.java
- src/main/java/com/floney/floney/book/dto/process/MyBookInfo.java
- src/main/java/com/floney/floney/book/dto/response/BookStatusResponse.java
- src/main/java/com/floney/floney/book/dto/response/InvolveBookResponse.java
- src/main/java/com/floney/floney/book/repository/BookUserRepositoryImpl.java
- src/main/java/com/floney/floney/book/service/BookService.java
- src/main/java/com/floney/floney/book/service/BookServiceImpl.java
> 171 feature 가계부 비활성화 여부 확인 api

- src/main/java/com/floney/floney/settlement/repository/SettlementCustomRepository.java
- src/main/java/com/floney/floney/settlement/repository/SettlementRepositoryImpl.java
- src/main/java/com/floney/floney/user/client/AppleClient.java
- src/main/java/com/floney/floney/user/client/ClientProxy.java
- src/main/java/com/floney/floney/user/client/GoogleClient.java
- src/main/java/com/floney/floney/user/client/KakaoClient.java
- src/main/java/com/floney/floney/user/client/dto/ApplePublicKey.java
- src/main/java/com/floney/floney/user/client/dto/ApplePublicKeys.java
- src/main/java/com/floney/floney/user/client/dto/AppleTokenHeader.java
- src/main/java/com/floney/floney/user/client/util/AppleOAuthPublicKeyGenerator.java
- src/main/java/com/floney/floney/user/controller/AppleController.java
- src/main/java/com/floney/floney/user/service/AppleUserService.java
- src/main/java/com/floney/floney/user/service/GoogleUserService.java
- src/main/java/com/floney/floney/user/service/KakaoUserService.java
> 170 feat: 애플 인증 API 구현

- src/main/java/com/floney/floney/user/entity/User.java
#183
- User.provider_id 길이 255자로 변경
- 내용
> 183 fix: User의 providerId 길이 255자로 수정

- src/main/java/com/floney/floney/book/dto/process/OurBookInfo.java
- src/main/java/com/floney/floney/book/dto/request/CreateBookRequest.java
- src/main/java/com/floney/floney/book/entity/Book.java
- src/main/java/com/floney/floney/book/service/BookLineServiceImpl.java
- src/main/java/com/floney/floney/book/service/BookServiceImpl.java
- src/test/java/com/floney/floney/book/BookFixture.java
- src/test/java/com/floney/floney/settlement/service/SettlementServiceTest.java
> 186 fix 이월설정 변경 미반영

- src/main/java/com/floney/floney/book/dto/process/OurBookInfo.java
- src/main/java/com/floney/floney/book/dto/request/CreateBookRequest.java
- src/main/java/com/floney/floney/book/entity/Book.java
- src/main/java/com/floney/floney/book/service/BookLineServiceImpl.java
- src/main/java/com/floney/floney/common/exception/common/ErrorControllerAdvice.java
- src/main/java/com/floney/floney/common/exception/user/CodeNotSameException.java
- src/main/java/com/floney/floney/user/service/UserService.java
- src/test/java/com/floney/floney/User/service/SubscribeServiceTest.java
- src/test/java/com/floney/floney/book/BookFixture.java
- src/test/java/com/floney/floney/settlement/service/SettlementServiceTest.java
> 188 fix: 이메일 인증 코드 불일치 시 에러 코드 변경

- src/main/java/com/floney/floney/user/controller/AppleController.java
- src/main/java/com/floney/floney/user/service/AppleUserService.java
- src/main/java/com/floney/floney/user/service/GoogleUserService.java
- src/main/java/com/floney/floney/user/service/KakaoUserService.java
- src/main/java/com/floney/floney/user/service/OAuthUserService.java
- src/main/java/com/floney/floney/user/service/UserService.java
> #190 feat: 간편 회원가입 로직 수정

- src/main/java/com/floney/floney/book/dto/process/CategoryFactory.java
- src/main/java/com/floney/floney/book/repository/category/CategoryCustomRepository.java
- src/main/java/com/floney/floney/book/repository/category/CategoryRepositoryImpl.java
> 194 fix 카테고리 에러

- src/main/java/com/floney/floney/book/controller/BookController.java
- src/main/java/com/floney/floney/book/dto/request/CreateBookRequest.java
- src/main/java/com/floney/floney/book/entity/Book.java
- src/main/java/com/floney/floney/book/repository/BookUserCustomRepository.java
- src/main/java/com/floney/floney/book/repository/BookUserRepositoryImpl.java
- src/main/java/com/floney/floney/book/service/BookService.java
- src/main/java/com/floney/floney/book/service/BookServiceImpl.java
- src/test/java/com/floney/floney/book/BookServiceTest.java
- src/test/java/com/floney/floney/fixture/BookFixture.java
> 198 fix 베타 테스트 에러 제보

- src/main/java/com/floney/floney/book/entity/Book.java
> #198 fix : 원시값 -> 참조값 변경

- src/main/java/com/floney/floney/book/controller/BookController.java
- src/main/java/com/floney/floney/book/dto/request/SaveAlarmRequest.java
- src/main/java/com/floney/floney/book/dto/request/UpdateAlarmReceived.java
- src/main/java/com/floney/floney/book/entity/Alarm.java
- src/main/java/com/floney/floney/book/repository/AlarmRepository.java
- src/main/java/com/floney/floney/book/repository/BookUserCustomRepository.java
- src/main/java/com/floney/floney/book/repository/BookUserRepositoryImpl.java
- src/main/java/com/floney/floney/book/service/BookService.java
- src/main/java/com/floney/floney/book/service/BookServiceImpl.java
- src/main/java/com/floney/floney/common/exception/book/NotFoundAlarmException.java
- src/main/java/com/floney/floney/common/exception/common/ErrorControllerAdvice.java
- src/main/java/com/floney/floney/common/exception/common/ErrorType.java
- src/main/java/com/floney/floney/user/dto/response/AlarmResponse.java
#203
<pre>
CREATE TABLE `alarm` (
`id` bigint NOT NULL AUTO_INCREMENT,
`created_at` datetime(6) DEFAULT NULL,
`status` varchar(255) DEFAULT NULL,
`updated_at` datetime(6) DEFAULT NULL,
`title` varchar(255) DEFAULT NULL,
`date` datetime(6) DEFAULT NULL,
`img_url` varchar(255) DEFAULT NULL,
`is_received` bit(1) DEFAULT b'0',
`book_id` bigint DEFAULT NULL,
`book_user_id` bigint DEFAULT NULL,
`body` varchar(45) DEFAULT NULL,
PRIMARY KEY (`id`),
KEY `FKkq6d3mec7wht1momfxf371jvs` (`book_id`),
KEY `FKq9fu5obatqc6u57tagxm5mggj` (`book_user_id`),
CONSTRAINT `FKkq6d3mec7wht1momfxf371jvs` FOREIGN KEY (`book_id`) REFERENCES `book` (`id`),
CONSTRAINT `FKq9fu5obatqc6u57tagxm5mggj` FOREIGN KEY (`book_user_id`) REFERENCES `book_user` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=utf8mb4 …
> 203 feature 알림 저장 조회 기능

- src/main/java/com/floney/floney/book/service/BookServiceImpl.java
#219
- 없음
- 이 메서드만 수정해 먼저 머지하고 나머지 for update도 고치도록 하겠습니다
> 219 fix: for update 시 트랜잭션 read only 설정 해제

- src/main/java/com/floney/floney/book/controller/BookController.java
- src/main/java/com/floney/floney/book/dto/request/AllOutcomesRequest.java
- src/main/java/com/floney/floney/book/repository/BookLineRepositoryImpl.java
- src/main/java/com/floney/floney/common/entity/BaseEntity.java
- src/main/java/com/floney/floney/common/exception/common/ErrorControllerAdvice.java
- src/main/java/com/floney/floney/common/exception/common/ErrorResponse.java
- src/main/java/com/floney/floney/common/exception/common/ErrorType.java
- src/main/java/com/floney/floney/settlement/dto/request/OutcomeRequest.java
- src/main/java/com/floney/floney/settlement/dto/request/SettlementRequest.java
- src/main/java/com/floney/floney/settlement/dto/response/SettlementResponse.java
- src/main/java/com/floney/floney/settlement/repository/SettlementRepository.java
- src/main/java/com/floney/floney/settlement/service/SettlementService.java
- src/main/java/com/floney/floney/user/controller/AppleController.java
- src/main/java/com/floney/floney/user/controller/GoogleController.java
- src/main/java/com/floney/floney/user/controller/KakaoController.java
- src/main/java/com/floney/floney/user/controller/UserController.java
- src/main/java/com/floney/floney/user/dto/request/EmailAuthenticationRequest.java
- src/main/java/com/floney/floney/user/dto/request/LoginRequest.java
- src/main/java/com/floney/floney/user/dto/request/SignoutRequest.java
- src/main/java/com/floney/floney/user/dto/request/SignupRequest.java
- src/main/java/com/floney/floney/user/dto/request/SubscribeRequest.java
- src/main/java/com/floney/floney/user/entity/User.java
- src/main/java/com/floney/floney/user/service/UserService.java
- src/test/java/com/floney/floney/fixture/UserFixture.java
- src/test/java/com/floney/floney/user/service/UserServiceTest.java
#221
- `user`에 `receive_marketing` 컬럼 추가
- 내용
> 221 fix: 카테고리 status 에러 및 기타 에러 해결

- src/main/java/com/floney/floney/user/dto/request/SignupRequest.java
> #224 fix: 간편 회원가입 시 비밀번호 받지 않도록 수정

- src/main/java/com/floney/floney/book/dto/request/DeleteCategoryRequest.java
- src/main/java/com/floney/floney/book/repository/BookLineCustomRepository.java
- src/main/java/com/floney/floney/book/repository/BookLineRepositoryImpl.java
- src/main/java/com/floney/floney/book/repository/CarryOverCustomRepositoryImpl.java
- src/main/java/com/floney/floney/book/repository/category/BookLineCategoryRepositoryImpl.java
- src/main/java/com/floney/floney/book/repository/category/CategoryCustomRepositoryImpl.java
- src/main/java/com/floney/floney/book/service/BookServiceImpl.java
- src/main/java/com/floney/floney/settlement/repository/SettlementUserCustomRepositoryImpl.java
> #228 fix: cross join이 발생하는 쿼리 수정

- src/main/java/com/floney/floney/book/controller/BookController.java
- src/main/java/com/floney/floney/book/service/BookService.java
- src/main/java/com/floney/floney/book/service/BookServiceImpl.java
> #233 refactor : 가계부 삭제 시, 최근 접근 가계부 키 갱신

- src/main/java/com/floney/floney/common/domain/vo/Mail.java
- src/main/java/com/floney/floney/common/exception/common/ErrorControllerAdvice.java
- src/main/java/com/floney/floney/common/exception/common/ErrorType.java
- src/main/java/com/floney/floney/common/exception/user/NotEmailUserException.java
- src/main/java/com/floney/floney/common/util/MailProvider.java
- src/main/java/com/floney/floney/user/controller/UserController.java
- src/main/java/com/floney/floney/user/domain/vo/RegeneratePasswordMail.java
- src/main/java/com/floney/floney/user/entity/User.java
- src/main/java/com/floney/floney/user/repository/UserRepository.java
- src/main/java/com/floney/floney/user/service/AuthenticationService.java
- src/main/java/com/floney/floney/user/service/UserService.java
- src/test/java/com/floney/floney/book/BookUserRepositoryTest.java
- src/test/java/com/floney/floney/fixture/UserFixture.java
- src/test/java/com/floney/floney/user/controller/UserControllerTest.java
- src/test/java/com/floney/floney/user/service/AuthenticationServiceTest.java
- src/test/java/com/floney/floney/user/service/SubscribeServiceTest.java
- src/test/java/com/floney/floney/user/service/UserServiceTest.java
> #226 fix: 비밀번호 재발급 시 유효성 검증 로직 추가

- src/main/java/com/floney/floney/book/entity/CarryOver.java
> #240 refactor : 카테고리 분기문 재처리

- build.gradle
- src/main/java/com/floney/floney/common/exception/common/ErrorControllerAdvice.java
- src/main/resources/logback-spring.xml
> 239 feature error 발생 시 slack 연동

- src/main/java/com/floney/floney/book/repository/BookLineRepositoryImpl.java
> #246 fix : 예산 설정 제외한 내역은 조회하지 않는 조건 추가

- src/main/java/com/floney/floney/book/dto/process/DayLine.java
> #248 fix : entity id 참조형 타입으로 변경

- src/main/java/com/floney/floney/book/dto/process/DayLines.java
- src/main/java/com/floney/floney/book/dto/request/AllOutcomesRequest.java
id가 null로 오는 이슈
#248 
- 내용
- 내용
> #248 fix : 일별 내역 조회 응답 DTO & 지출 내역 조회 응답 DTO 분리

- .github/workflows/gradle.yml
> #251 chore: 빌드 시 logs 폴더 추가

- src/main/java/com/floney/floney/book/repository/BookLineCustomRepository.java
- src/main/java/com/floney/floney/book/repository/BookLineRepositoryImpl.java
- src/main/java/com/floney/floney/book/service/BookLineServiceImpl.java
- src/main/java/com/floney/floney/book/service/category/CategoryFactory.java
- src/test/java/com/floney/floney/book/BookLineRepositoryTest.java
- src/test/java/com/floney/floney/book/CategoryFixture.java
> 238 refactor 카테고리 조회 로직 변경 1

- src/main/java/com/floney/floney/book/service/BookServiceImpl.java
#256
- 내용
- 이전 256 PR에서 처리 안된 부분이 있어 보완했습니다
> 256 fix 가계부 나가기시 사용자 비활성화

- src/main/java/com/floney/floney/common/config/SecurityConfig.java
- src/main/java/com/floney/floney/user/controller/UserController.java
- src/test/java/com/floney/floney/user/controller/UserControllerTest.java
> #263 refactor: 회원 가입 및 회원 탈퇴 API 엔드포인트 수정

- src/main/java/com/floney/floney/common/exception/common/ErrorControllerAdvice.java
- src/main/java/com/floney/floney/user/controller/UserController.java
- src/main/java/com/floney/floney/user/dto/request/UpdatePasswordRequest.java
- src/main/java/com/floney/floney/user/service/AuthenticationService.java
- src/main/java/com/floney/floney/user/service/UserService.java
- src/test/java/com/floney/floney/user/service/AuthenticationServiceTest.java
- src/test/java/com/floney/floney/user/service/UserServiceTest.java
> #267 비밀번호 변경 API 에러 수정

- src/main/java/com/floney/floney/book/domain/entity/Book.java
- src/main/java/com/floney/floney/book/repository/BookUserCustomRepository.java
- src/main/java/com/floney/floney/book/repository/BookUserRepositoryImpl.java
- src/main/java/com/floney/floney/book/service/BookServiceImpl.java
- src/main/java/com/floney/floney/user/service/UserService.java
> 269 feature 방장 탈퇴시 위임로직 추가

- src/main/java/com/floney/floney/analyze/dto/process/BookAnalyzer.java
- src/main/java/com/floney/floney/analyze/service/AnalyzeServiceImpl.java
- src/main/java/com/floney/floney/book/repository/category/CategoryCustomRepository.java
- src/main/java/com/floney/floney/book/repository/category/CategoryCustomRepositoryImpl.java
- src/main/java/com/floney/floney/book/service/category/CategoryServiceImpl.java
- src/test/java/com/floney/floney/book/CategoryRepositoryTest.java
> 266 feature 카테고리 삭제 시 전체 내역 삭제 & 분석 현재 자산 값 변경

- src/main/java/com/floney/floney/book/dto/request/CreateBookRequest.java
- src/main/java/com/floney/floney/book/repository/category/CategoryCustomRepository.java
- src/main/java/com/floney/floney/book/repository/category/CategoryCustomRepositoryImpl.java
- src/main/java/com/floney/floney/book/service/category/CategoryServiceImpl.java
#266
- seeProfile default값 1로 수정
- 내용
> 266 fix 카테고리 삭제 시 전체 내역 삭제, 내역 프로필 보기 

- src/main/java/com/floney/floney/user/entity/User.java
> #277 fix: 회원탈퇴 시 provider id 삭제 안되던 오류 수정

- src/main/java/com/floney/floney/user/controller/UserController.java
- src/main/java/com/floney/floney/user/dto/response/ReceiveMarketingResponse.java
- src/main/java/com/floney/floney/user/service/UserService.java
- src/test/java/com/floney/floney/user/service/UserServiceTest.java
> #290 feat: 회원 마케팅 수신 동의 여부 조회 API 구현

- src/main/java/com/floney/floney/user/controller/UserController.java
- src/main/java/com/floney/floney/user/dto/request/PasswordAuthenticateRequest.java
- src/main/java/com/floney/floney/user/entity/User.java
- src/main/java/com/floney/floney/user/service/AuthenticationService.java
- src/test/java/com/floney/floney/user/controller/UserControllerTest.java
> #275 feat: 비밀번호 확인 API 구현

- src/main/java/com/floney/floney/analyze/service/AssetServiceImpl.java
- src/main/java/com/floney/floney/analyze/service/CarryOverServiceImpl.java
> #293 fix : 이체 내역이라면 이월,자산 반영 X

- src/main/java/com/floney/floney/book/repository/BookCustomRepository.java
- src/main/java/com/floney/floney/book/repository/BookCustomRepositoryImpl.java
- src/main/java/com/floney/floney/user/controller/UserController.java
- src/main/java/com/floney/floney/user/dto/response/SignoutResponse.java
- src/main/java/com/floney/floney/user/service/UserService.java
- src/test/java/com/floney/floney/fixture/BookFixture.java
- src/test/java/com/floney/floney/user/service/UserServiceTest.java
> #292 feature: 회원탈퇴 API 응답 추가

- src/main/java/com/floney/floney/analyze/service/AssetService.java
- src/main/java/com/floney/floney/analyze/service/AssetServiceImpl.java
- src/main/java/com/floney/floney/analyze/service/CarryOverService.java
- src/main/java/com/floney/floney/analyze/service/CarryOverServiceImpl.java
- src/main/java/com/floney/floney/book/controller/BookController.java
- src/main/java/com/floney/floney/book/domain/entity/Asset.java
- src/main/java/com/floney/floney/book/domain/entity/BookLine.java
- src/main/java/com/floney/floney/book/domain/entity/CarryOver.java
- src/main/java/com/floney/floney/book/dto/request/BookLineRequest.java
- src/main/java/com/floney/floney/book/repository/analyze/AssetCustomRepository.java
- src/main/java/com/floney/floney/book/repository/analyze/AssetCustomRepositoryImpl.java
- src/main/java/com/floney/floney/book/repository/analyze/AssetRepository.java
- src/main/java/com/floney/floney/book/repository/analyze/CarryOverRepository.java
- src/main/java/com/floney/floney/book/service/BookLineService.java
- src/main/java/com/floney/floney/book/service/BookLineServiceImpl.java
- src/main/java/com/floney/floney/book/service/BookServiceImpl.java
- src/main/java/com/floney/floney/book/service/category/CategoryFactory.java
- src/test/java/com/floney/floney/fixture/BookLineFixture.java
#293
- 내용
생각해보니 가계부 초기화는 또 다른 로직이 필요해서(아예 쌓은 자산 비활성화), 추가하였습니다.
> 293 fix 가계부 초기화 시 자산 초기화

- src/main/java/com/floney/floney/user/controller/UserController.java
- src/test/java/com/floney/floney/user/controller/UserControllerTest.java
> #297 fix: 회원 비밀번호 검사 API http method 변경

- .github/workflows/develop-cd.yml
- .github/workflows/gradle-build.yml
- .github/workflows/gradle.yml
- .github/workflows/main-cd.yml
- script/start.sh
- script/stop.sh
#286
- 없음
- CI: 테스트 결과가 PR 댓글에 달리는 기능을 추가했습니다
- 운영 CD: main 브랜치에 머지되어야 결과를 확인할 수 있어서 아직은 테스트 못했습니다
> #286 main 브랜치 CD 설정 & 기타 설정 수정

- .github/workflows/main-cd.yml
> #303 hotfix: 운영 start.sh 파일 저장 방식 변경

- script/stop.sh
> #311 fix: 현재 서비스 프로세스 id 찾는 명령어 수정

- src/main/resources/logback-spring.xml
> #315 : 개발 서버 알람, 실 서버 알람 분리

- script/stop.sh
- src/main/resources/logback-spring.xml
> deploy: 운영 서버 배포

- src/main/java/com/floney/floney/common/config/SecurityConfig.java
- src/main/java/com/floney/floney/common/controller/CheckController.java
- src/main/java/com/floney/floney/common/controller/HealthCheckController.java
#313
- 없음
- 패키지 위치나 클래스 이름을 이렇게 해도 되나? 싶은데 좋은 대안 있으면 추천 부탁드려요
> #313 feat: 서버 상태 확인용 API 구현

- .gitignore
- src/main/resources/console-appender.xml
- src/main/resources/file-error-appender.xml
- src/main/resources/file-info-appender.xml
- src/main/resources/file-warn-appender.xml
- src/main/resources/logback-spring.xml
- src/main/resources/slack-error-appender.xml
#318
- 내용
- 수동 테스트로 진행할 땐, 잘 생성이 되었습니다
> #318 fix : Logger 파일 미출력 이슈로 인한 xml 변경

- src/main/resources/logback-spring.xml
> #318 fix : console appender 추가

- .github/workflows/develop-cd.yml
- .github/workflows/main-cd.yml
- .gitignore
- .gitmodules
- src/main/java/com/floney/floney/infra/googleAlarm/client/GoogleGoogleTokenProvider.java
- src/main/resources/application.yaml
설정 파일 관리 방식을 github secrets에서 git submodule로 변경한다.
- 설정 파일 submodule 추가
- `application.yaml` 관리 방식 변경
> #333 feat: submodule 추가

- src/main/java/com/floney/floney/analyze/service/AssetServiceImpl.java
- src/main/java/com/floney/floney/book/repository/analyze/AssetCustomRepository.java
- src/main/java/com/floney/floney/book/repository/analyze/AssetCustomRepositoryImpl.java
main → develop 업데이트
- #344 
- #339
> deploy: main → develop

- build.gradle
- src/main/java/com/floney/floney/common/config/SecurityConfig.java
모니터링 서버 구축용 웹 서버 환경설정
- 우선 해당 환경 설정이 ec2에 올라가야지 아후 구축을 할 수 있어서 develop 서버에서 테스트 후 , 실제 운영서버에 이관하겠습니다.
> #321 feat: 모니터링 서버 구축

- src/main/java/com/floney/floney/common/exception/common/ErrorControllerAdvice.java
에러 레벨 수정 및 메세지 수정
- log 레벨 수정 : error -> warn
- 메세지 수정  : id가 아닌 data
> #353 refactor : AlreadyExistException 로그 메세지, 레벨 수정

- script/start.sh
배포 명령어를 수정
- `start.sh` 내 배포 명령어를 수정
> #359 배포 명령어 수정

- src/main/java/com/floney/floney/book/service/ExcelServiceImpl.java
엑셀 날짜 데이터 숫자 포맷 -> date포맷으로 변경
엑셀 date포맷으로 날짜 추출 변경
> #367 fix : 엑셀 date포맷으로 날짜 추출 변경

- src/main/java/com/floney/floney/book/domain/constant/ExcelDuration.java
- src/main/java/com/floney/floney/common/domain/vo/DateDuration.java
엑셀 추출 범위(작년) 추가
기획 추가로 인한 엑셀 추출 범위(작년) 추가
> #376 feat : 엑셀 추출 범위(작년) 추가

- src/main/java/com/floney/floney/book/repository/BookLineCustomRepository.java
- src/main/java/com/floney/floney/book/repository/BookLineRepositoryImpl.java
- src/main/java/com/floney/floney/book/service/ExcelServiceImpl.java
엑셀 추출 시 최근 날짜부터 정렬
- 엑셀 추출 시 최근 날짜부터 정렬
> #378 feat : 엑셀 추출 시 최근 날짜부터 정렬

- src/test/resources/logback-test.xml
test 환경 logback 설정 추가
- test에서는 console이 찍히게끔 수정
- 추가적으로 일자별로 안나뉜 현상은 https://github.com/Floney-2023/Floney-Server/discussions/390 여기에 작성해놨습니다.
(제가 완전 오해하고 있었어요)
> #388 feat : test 환경 logback 설정 추가

- src/main/resources/db/migration/mysql/V7__add_category_tables.sql
- src/main/resources/db/migration/mysql/V8__migrate_category.sql
카테고리 마이그레이션 관련 에러를 수정했다.
- 마이그레이션 시 `created_at` 은 값을 유지하도록 변경
- `book_line_category` 테이블 마이그레이션 에러 해결
- 개발 RDS 주소 변경
- MySQL 이벤트 수정 ([해당 댓글 참고](https://github.com/Floney-2023/Floney-Server/pull/394#issuecomment-1968506687))
> #389 fix: 카테고리 마이그레이션 관련 에러 수정

- src/main/java/com/floney/floney/book/domain/RepeatDuration.java
- src/main/java/com/floney/floney/book/domain/entity/RepeatBookLine.java
- src/main/java/com/floney/floney/book/dto/process/BookLineWithWriterView.java
- src/main/java/com/floney/floney/book/dto/response/RepeatBookLineResponse.java
- src/main/java/com/floney/floney/book/repository/BookLineRepositoryImpl.java
- src/main/java/com/floney/floney/book/service/BookLineServiceImpl.java
- src/test/java/com/floney/floney/acceptance/BookAcceptanceTest.java
- src/test/java/com/floney/floney/acceptance/fixture/BookApiFixture.java
- src/test/java/com/floney/floney/book/domain/entity/RepeatBookLineTest.java
- src/test/java/com/floney/floney/book/repository/BookLineCustomRepositoryTest.java
일별 내역 조회 시, 반복 내역 조회
-  일별 내역 조회 시, 반복 내역 조회
> #401 refactor : 일별 내역 조회 시, 반복 내역 조회

- src/main/java/com/floney/floney/analyze/service/CarryOverServiceImpl.java
- src/main/java/com/floney/floney/book/repository/analyze/CarryOverRepository.java
- src/main/resources/db/migration/mysql/V12__add_unique_key_in_carry_over.sql
- src/test/java/com/floney/floney/book/service/CarryOverServiceTest.java
> #407 fix: 이월설정 동시성 처리

- src/main/java/com/floney/floney/analyze/service/AssetServiceImpl.java
- src/main/java/com/floney/floney/book/domain/entity/BookLine.java
- src/main/java/com/floney/floney/book/service/BookLineServiceImpl.java
- src/test/java/com/floney/floney/book/domain/entity/BookLineTest.java
- src/test/java/com/floney/floney/book/domain/entity/RepeatBookLineTest.java
수입 내역일 경우 자산에서 제외를 선택한다면 자산에 금액을 미반영한다.
현재 운영서버 또한 이슈가 발생하고 있다
> #420 fix: 자산에서 제외 기능이 비정상 동작

- src/main/java/com/floney/floney/analyze/service/AssetServiceImpl.java
자산이 6개월이 아닌 5개월이 반환됨.
- 등호가 빠져있어, 추가
> #422 fix : 반복문 자산 반환 기간 조건 수정

- src/main/java/com/floney/floney/book/repository/category/SubcategoryCustomRepository.java
- src/main/java/com/floney/floney/book/repository/category/SubcategoryRepository.java
- src/main/java/com/floney/floney/book/repository/category/SubcategoryRepositoryImpl.java
- src/main/java/com/floney/floney/book/service/category/CategoryServiceImpl.java
- src/test/java/com/floney/floney/book/repository/category/SubcategoryRepositoryTest.java
Subcategory 추가 및 삭제 에러를 해결했다.
- 추가 시 unique index로 인한 DB 에러 핸들링 추가
- 삭제 시 unique index로 인한 중복 INACTIVE 데이터 처리 로직 추가
> #430 fix: Subcategory 추가 및 삭제 에러 해결

- src/main/java/com/floney/floney/analyze/service/AnalyzeServiceImpl.java
- src/main/java/com/floney/floney/book/repository/analyze/BudgetRepository.java
- src/main/java/com/floney/floney/book/service/BookServiceImpl.java
분석 - 예산 조회 시, ACTIVE 조건 추가
분석 - 예산 조회 시, ACTIVE 조건 추가
> #434 fix : 예산 조회 시, ACTIVE 조건 추가

- src/main/resources/db/migration/mysql/V15__add_index_in_book.sql
- src/test/java/com/floney/floney/book/service/BookServiceTest.java
- src/test/java/com/floney/floney/fixture/BookFixture.java
`book.code` 에 인덱스 추가
- `book.code` 에 인덱스 추가
> #436 fix: `book.code` 에 인덱스 추가

- src/main/java/com/floney/floney/book/repository/BookUserRepositoryImpl.java
- src/test/java/com/floney/floney/book/repository/BookUserCustomRepositoryTest.java
`마이페이지 내 가계부 조회 쿼리` 에서 무조건 가계부원 수가 하나로 반환되던 결과를 수정
- 잘못된 쿼리 수정
- 해당 쿼리에 대한 테스트 추가
> #445 hotfix: 마이페이지의 내 가계부 팀원 수 에러 해결

- src/main/java/com/floney/floney/book/domain/Currency.java
사용자의 요청에 따른 다양한 종류의 화폐 단위 추가
- 화폐단위 추가
> #441 feat : 화폐 단위 추가

- src/main/java/com/floney/floney/book/repository/BookLineRepositoryImpl.java
- src/test/java/com/floney/floney/book/repository/BookLineCustomRepositoryTest.java
일별 내역 조회시, 사용자가 최근에 추가한 내역부터 보여진다
> #453 feature : 일별 내역 조회 시 정렬

- src/main/java/com/floney/floney/common/util/JwtProvider.java
- src/test/resources/application.yaml
jwt 만료 시간을 `application.yaml` 에서 조절하도록 수정했다.
- develop과 기본 `application.yaml` 파일 수정
- 테스트 `application.yaml` 파일 수정
> #456 refactor: jwt 만료 시간을 `application.yaml` 에서 조절

- src/main/java/com/floney/floney/book/domain/entity/BookLine.java
- src/main/java/com/floney/floney/book/domain/entity/RepeatBookLine.java
- src/main/java/com/floney/floney/book/service/BookLineServiceImpl.java
- src/main/java/com/floney/floney/book/util/DateUtil.java
- src/test/java/com/floney/floney/acceptance/BookAcceptanceTest.java
- src/test/java/com/floney/floney/fixture/BookRequestDtoFixture.java
반복 기준과 내역 날짜의 정합성을 맞춘다
가계부 내역 생성시, 반복 내역이라면, 날짜를 재 계산하여 내역을 생성한다
> #450 feature: 반복 기준에 맞는 내역 생성

- src/main/java/com/floney/floney/common/config/LogByAop.java
상태 체크 API는 로깅 대상에서 제외했다.
- `LogByAop` 의 aop 대상 수정
- dev 환경 JWT 만료 시간 확대
> #464 feat: 상태 체크 API는 로깅 대상에서 제외

- src/main/java/com/floney/floney/book/controller/FavoriteController.java
- src/main/java/com/floney/floney/book/domain/category/CategoryType.java
- src/main/java/com/floney/floney/book/domain/category/entity/Category.java
- src/main/java/com/floney/floney/book/repository/BookLineRepositoryImpl.java
- src/main/java/com/floney/floney/book/repository/favorite/FavoriteRepository.java
- src/main/java/com/floney/floney/book/service/FavoriteService.java
- src/main/java/com/floney/floney/book/service/FavoriteServiceImpl.java
- src/main/java/com/floney/floney/common/exception/book/FavoriteNotFoundException.java
- src/main/java/com/floney/floney/common/exception/common/ErrorControllerAdvice.java
- src/main/java/com/floney/floney/common/exception/common/ErrorType.java
- src/test/java/com/floney/floney/acceptance/FavoriteAcceptanceTest.java
- src/test/java/com/floney/floney/acceptance/fixture/FavoriteApiFixture.java
즐겨찾기 조회 API 구현
- 즐겨찾기 단건 조회 API 구현
- 즐겨찾기 카테고리 별 조회 API 구현
- 관련 인수 테스트 추가
> #462 feat: 즐겨찾기 조회

- src/main/java/com/floney/floney/book/controller/FavoriteController.java
- src/main/java/com/floney/floney/book/service/FavoriteService.java
- src/main/java/com/floney/floney/book/service/FavoriteServiceImpl.java
- src/test/java/com/floney/floney/acceptance/FavoriteAcceptanceTest.java
즐겨찾기 삭제 API를 구현했다.
- 즐겨찾기 삭제 API 구현
- 관련 인수 테스트 추가
> #466 feat: 즐겨찾기 삭제

- src/main/java/com/floney/floney/book/repository/favorite/FavoriteCustomRepository.java
- src/main/java/com/floney/floney/book/repository/favorite/FavoriteRepository.java
- src/main/java/com/floney/floney/book/repository/favorite/FavoriteRepositoryImpl.java
- src/main/java/com/floney/floney/book/service/BookServiceImpl.java
- src/main/java/com/floney/floney/book/service/category/CategoryServiceImpl.java
- src/test/java/com/floney/floney/acceptance/BookAcceptanceTest.java
- src/test/java/com/floney/floney/acceptance/CategoryAcceptanceTest.java
- src/test/java/com/floney/floney/acceptance/fixture/FavoriteApiFixture.java
가계부 삭제시 , 카테고리 삭제 시 즐겨찾기를 삭제한다
가계부 삭제시 , 카테고리 삭제 시 즐겨찾기를 삭제한다
> #460 feat: 가계부 삭제, 카테고리 삭제 시 즐겨찾기 삭제

- src/main/java/com/floney/floney/book/domain/Currency.java
> fix: 태국화폐 변경

- src/main/java/com/floney/floney/book/service/FavoriteServiceImpl.java
- src/test/java/com/floney/floney/acceptance/FavoriteAcceptanceTest.java
즐겨찾기 추가 시 exceptStatus 도 반영하도록 수정했다.
- 변화 내용
> #478 fix: 즐겨찾기 추가 시 exceptStatus 도 반영하도록 수정

- .github/workflows/develop-cd.yml
AWS 계정 이동에 따라 dev cd 스크립트를 수정했다.
- 변화 내용
> #481 chore: dev cd 스크립트 수정

- src/main/resources/db/migration/mysql/V18__add_unique_index_in_budget.sql
```java
Optional<Budget> findBudgetByBookAndDateAndStatus(Book savedBook, LocalDate date, Status status);
```
에서 여러 개의 결과가 나와 에러가 발생하던 현상을 수정했습니다.
- budget 에 유니크 인덱스 추가
> #485 hotfix: budget 에 유니크 인덱스 추가

- src/main/java/com/floney/floney/book/controller/BookController.java
- src/main/java/com/floney/floney/book/repository/BookLineCustomRepository.java
- src/main/java/com/floney/floney/book/repository/BookLineRepositoryImpl.java
- src/main/java/com/floney/floney/book/service/BookServiceImpl.java
> #492 hotfix : 반복 내역 삭제 로직 수정

- .github/CODEOWNERS
- .github/workflows/main-cd.yml
- script/start.sh
- script/stop.sh
배포 설정을 수정했습니다.
- 홈 디렉토리 변수로 받도록 변경
- spring profiles 변수로 받도록 변경
- EC2 인스턴스에서 환경 변수 추가하고 PR 배포할 예정입니다.
> #497 chore: 배포 설정 수정

- appspec.yml
이전 PR(#498) 에서 변경 못한 부분을 수정했습니다.
- 변화 내용
> #497 chore: 변경된 ec2 설정에 따라 `appspec.yml` 수정

- appspec.yml
홈디렉토리 관련 CD 에러를 수정합니다.
- 변화 내용
> #497 chore: CD 설정 해결

- appspec.yml
해당 오류를 해결하기 위해 경로를 수정합니다.
- 변화 내용
> #497 chore: 상대 경로 수정

- README.md
- src/main/java/com/floney/floney/book/repository/analyze/BudgetCustomRepository.java
- src/main/java/com/floney/floney/book/repository/analyze/BudgetCustomRepositoryImpl.java
- src/main/java/com/floney/floney/book/service/BookServiceImpl.java
- src/test/java/com/floney/floney/book/repository/BudgetCustomRepositoryTest.java
예산 논리 삭제 -> 물리 삭제 변경
- 예산을 물리 삭제 한다.
> #505 hotfix : 예산 물리 삭제 변경

- .github/workflows/main-cd.yml
- script/start.sh
> #505 fix: main-cd 수정

- src/main/java/com/floney/floney/analyze/controller/AnalyzeController.java
- src/main/java/com/floney/floney/analyze/domain/BookLineSortingType.java
- src/main/java/com/floney/floney/analyze/dto/request/AnalyzeBySubcategoryRequest.java
- src/main/java/com/floney/floney/analyze/dto/response/AnalyzeResponseBySubcategory.java
- src/main/java/com/floney/floney/analyze/dto/response/BookLineResponse.java
- src/main/java/com/floney/floney/analyze/service/AnalyzeService.java
- src/main/java/com/floney/floney/analyze/service/AnalyzeServiceImpl.java
- src/main/java/com/floney/floney/book/domain/BookLines.java
- src/main/java/com/floney/floney/book/repository/BookLineCustomRepository.java
- src/main/java/com/floney/floney/book/repository/BookLineRepositoryImpl.java
- src/main/java/com/floney/floney/common/domain/vo/DateDuration.java
> #513 feat: 지출 및 수입 상세 내역 조회
