Floney-2023/Floney-Server

- src/main/java/com/floney/floney/user/client/ClientProxy.java
- src/main/java/com/floney/floney/user/client/GoogleClient.java
- src/main/java/com/floney/floney/user/client/KakaoClient.java
- src/main/java/com/floney/floney/user/controller/AuthController.java
- src/main/java/com/floney/floney/user/controller/GoogleController.java
- src/main/java/com/floney/floney/user/controller/KakaoController.java
- src/main/java/com/floney/floney/user/controller/UserController.java
- src/main/java/com/floney/floney/user/dto/request/SignupRequest.java
- src/main/java/com/floney/floney/user/dto/response/GoogleUserResponse.java
- src/main/java/com/floney/floney/user/dto/response/KakaoUserResponse.java
- src/main/java/com/floney/floney/user/entity/User.java
- src/main/java/com/floney/floney/user/repository/UserRepository.java
- src/main/java/com/floney/floney/user/service/GoogleUserService.java
- src/main/java/com/floney/floney/user/service/KakaoUserService.java
- src/main/java/com/floney/floney/user/service/OAuthUserService.java
- src/test/java/com/floney/floney/User/controller/UserControllerTest.java
#17
- User에 providerId 추가
- 프론트랑 직접 테스팅 해봐야 함
- 일반 회원과 간편 회원 간 이메일 충돌 처리 해야함
> #17 feat: 간편 로그인 email -> auth id로 유저 식별 기준 변경

- src/main/java/com/floney/floney/common/exception/common/ErrorControllerAdvice.java
- src/main/java/com/floney/floney/common/exception/common/ErrorType.java
- src/main/java/com/floney/floney/common/exception/user/SignoutOtherReasonEmptyException.java
- src/main/java/com/floney/floney/settlement/repository/SettlementRepository.java
- src/main/java/com/floney/floney/user/controller/UserController.java
- src/main/java/com/floney/floney/user/dto/constant/SignoutType.java
- src/main/java/com/floney/floney/user/dto/request/SignoutRequest.java
- src/main/java/com/floney/floney/user/entity/SignoutOtherReason.java
- src/main/java/com/floney/floney/user/entity/SignoutReason.java
- src/main/java/com/floney/floney/user/repository/SignoutOtherReasonRepository.java
- src/main/java/com/floney/floney/user/repository/SignoutReasonCustomRepository.java
- src/main/java/com/floney/floney/user/repository/SignoutReasonCustomRepositoryImpl.java
- src/main/java/com/floney/floney/user/repository/SignoutReasonRepository.java
- src/main/java/com/floney/floney/user/service/UserService.java
- src/test/java/com/floney/floney/user/controller/UserControllerTest.java
- src/test/java/com/floney/floney/user/repository/SignoutReasonRepositoryTest.java
- src/test/java/com/floney/floney/user/service/UserServiceTest.java
#204
```sql
CREATE TABLE `signout_reason` (
`id` bigint NOT NULL AUTO_INCREMENT,
`created_at` datetime(6) NOT NULL,
`status` varchar(255) NOT NULL,
`updated_at` datetime(6) NOT NULL,
`count` bigint NOT NULL DEFAULT '0',
`reason_type` varchar(255) NOT NULL,
PRIMARY KEY (`id`),
UNIQUE KEY `UK_9f1ps6trvqboiwiblcxy8t5cr` (`reason_type`)
) ENGINE=InnoDB AUTO_INCREMENT=7 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci
CREATE TABLE `signout_other_reason` (
`id` bigint NOT NULL AUTO_INCREMENT,
`created_at` datetime(6) NOT NULL,
`status` varchar(255) NOT NULL,
`updated_at` datetime(6) NOT NULL,
`reason` varchar(255) NOT NULL,
PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci
insert into signout_reason (reason_type, status, created_at, …
```
> 204 feat: 회원 탈퇴 사유 저장

- src/main/java/com/floney/floney/settlement/controller/SettlementController.java
- src/main/java/com/floney/floney/settlement/service/SettlementService.java
- src/test/java/com/floney/floney/settlement/service/SettlementServiceTest.java
#268
- 없음
- 처음에는 인터셉터나 AOP를 사용하려고 했는데, 이게 요청마다 bookKey를 주는 방식이 다르고 & 어떤 API에는 이미 검사하는 메서드가 포함되어 있어서 우선 정산 쪽만 검사 메서드를 추가하는 방식으로 구현했습니다. 추후 리팩토링 or 가계부 쪽 API에도 추가하겠습니다..
> #268 feat: 정산 API에 요청자가 가계부 유저인지 검사하는 로직 추가

- src/main/java/com/floney/floney/analyze/service/AnalyzeServiceImpl.java
- src/main/java/com/floney/floney/book/repository/BookCustomRepositoryImpl.java
- src/main/java/com/floney/floney/book/repository/BookLineCustomRepository.java
- src/main/java/com/floney/floney/book/repository/BookLineRepositoryImpl.java
- src/main/java/com/floney/floney/book/repository/category/CategoryCustomRepository.java
- src/main/java/com/floney/floney/book/repository/category/CategoryCustomRepositoryImpl.java
- src/test/java/com/floney/floney/book/BookLineRepositoryTest.java
#325
[에러 원인]
- 카테고리의 '이름'으로 쿼리문에서 조건을 걸다보니, 기타 와 미분류 처럼 부모가 다르지만 자식끼리 이름이 같은 경우, 중복된 값이 잡히고 있었습니다.
[해결 방안]
따라서, name이 아닌, entity자체로 비교하는 것으로 변경하였습니다
- 테스트 코드를 짜다가, 카테고리 리팩토링이 들어가고 있는 것으로 알아서, 포함시키지 않았습니다
> #325 fix : 분석 카테고리 조회 시, 이름이 아닌 객체 자체를 쿼리문에 조건으로 지정

- script/start.sh
#318
- 내용
[로그 파일이 생기지 않은 원인 파악]
- 수동으로 빌드 할 때 항상 잘 된 이유 -> 제가 빌드를 실행하는 경로는 Floney_server 폴더 내입니다. 
- Ec2에서 github action이 파일을 실행하는 경로는 root입니다. 하지만 root에서는 폴더를 생성하기 위해서는 관리자 권한이 필요합니다
1. root 위치에서 start.sh에 기재된 명령어를 치고 수동으로 빌드 시 다음과 같은 에러가 납니다
2. root경로에서 mkdir 명령어를 작성하면 permission denied가 발생합니다.(이 이유 때문에 예전에 mkdir이 수행 안된듯 합니다)
3. 따라서 sudo 권한을 주어 명령어를 실행해야 정상적으로 로그 파일이 생깁니다.
> #318 fix : 관리자 권한으로 빌드 실행

- src/main/java/com/floney/floney/analyze/service/AssetService.java
- src/main/java/com/floney/floney/analyze/service/AssetServiceImpl.java
- src/main/java/com/floney/floney/analyze/service/BookDeletedEventHandler.java
- src/main/java/com/floney/floney/book/domain/entity/Asset.java
- src/main/java/com/floney/floney/book/domain/entity/BookLine.java
- src/main/java/com/floney/floney/book/dto/constant/CategoryEnum.java
- src/main/java/com/floney/floney/book/dto/response/BookLineResponse.java
- src/main/java/com/floney/floney/book/repository/analyze/AssetCustomRepository.java
- src/main/java/com/floney/floney/book/repository/analyze/AssetCustomRepositoryImpl.java
- src/main/java/com/floney/floney/book/repository/analyze/AssetRepository.java
- src/main/java/com/floney/floney/book/service/BookLineServiceImpl.java
- src/main/java/com/floney/floney/book/service/BookServiceImpl.java
- src/main/resources/schema.sql
- src/test/java/com/floney/floney/book/MonthLineResponseTest.java
- src/test/java/com/floney/floney/fixture/BookLineFixture.java
- src/test/resources/application.yaml
#319
- 없음
- 에러 원인: 가계부 내역 id & 날짜가 같은 자산 데이터가 예상과 달리 여러 개 생기는 경우가 있었고, 이를 조회할 때 데이터가 하나가 아니라 SQL 에러가 발생함
- 이유는 정확하지 않지만, 자산 생성 or 삭제 코드를 보면 중간에 데이터의 갱신 손실이 일어날 가능성이 있었습니다. 이를 비관적 락을 걸어서 막았습니다. 날짜가 이른 순서대로 락이 걸려서 데드락이 발생할 것 같지는 않은데 어떻게 생각하세요?
> #319 hotfix: 자산 삭제 시 에러 해결

- src/main/java/com/floney/floney/book/repository/analyze/AssetRepository.java
자산 upsert 쿼리에서 테이블 이름을 소문자로 변경
- EC2 운영체제에서 에러가 나지 않기 위해 대문자로 되어있던 테이블 이름을 소문자로 변경
> #335 hotfix: 자산 upsert 쿼리에서 테이블 이름을 소문자로 변경

- src/main/java/com/floney/floney/analyze/service/AssetServiceImpl.java
내역 추가/수정에 따른 자산 추가 시 지출(OUTCOME)이면 (-)로 추가하도록 수정
- 지출(OUTCOME)이면 (-)로 자산 데이터가 갱신/생성 되도록 수정
> #339 hotfix: OUTCOME인 내역은 자산을 (-)로 추가하도록 수정

- src/main/java/com/floney/floney/analyze/service/AssetServiceImpl.java
- src/main/java/com/floney/floney/book/repository/analyze/AssetCustomRepository.java
- src/main/java/com/floney/floney/book/repository/analyze/AssetCustomRepositoryImpl.java
- src/main/java/com/floney/floney/user/service/AuthenticationService.java
자산 제외 시 가계부 내역 유형(수입/지출)에 따라 부호가 반대로 연산되던 현상을 수정
- `subtractMoneyByDateAndBook` 로 쿼리 메서드 이름 변경
- 자산 추가 & 제외 시 필요한 부호 통일
> #334 hotfix: subtractAssetOf 메서드에서 부호가 반대로 연산되던 문제 수정

- appspec.yml
- src/main/resources/schema.sql
Code Deploy 빌드 시 권한 777 부여
755 권한으로 인해, 다른 사용자는 해당 파일에 권한이 없어 로그 파일이 안생기나? 라는 가정을 통해 777권한을 줘보게 되었습니다..
> #318 fix : 빌드 시 권한 777 부여

- src/main/java/com/floney/floney/book/service/category/CategoryServiceImpl.java
- src/main/java/com/floney/floney/common/exception/book/AlreadyExistException.java
- src/main/java/com/floney/floney/common/exception/common/ErrorControllerAdvice.java
- src/main/java/com/floney/floney/common/exception/common/ErrorType.java
카테고리 중복을 방지하기 위한 검사 메서드 추가
다음과 같이 중복된 이름의 카테고리를 추가하면, 에러가 반환되게끔 수정했습니다.
기존 오기입 된 카테고리는 운영서버 DB에서 수동으로 지울 예정입니다.
> #342 hotfix : 카테고리 중복 생성 방지 검사 추가

- src/main/resources/file-error-appender.xml
- src/main/resources/file-info-appender.xml
- src/main/resources/file-warn-appender.xml
- src/main/resources/logback-spring.xml
Logger 폴더 크기 조절, 및 xml 코드 정리
- Logger 폴더 생성 시 일정 크기 넘어가면 압축
- 30일까지 보관 후, 삭제
- 일치하는 level만 해당 파일에 log작성하도록 ex. error 폴더에는 error만
단, 현재는 전반적으로 log메세지가 명확하지 않은 상태이므로, 에러가 터지면 앞 뒤 맥락을 파악하기 어려움.
따라서 info 폴더 출력시에만 전체 흐름을 보기 위해 모든 레벨을 출력하도록 설정(info,warn,error)
차후에 log메세지를 명확히 수정 후, info 에 level 제한을 걸 예정(#318 머지 후)
> #368 refactor: logger 파일 보완

- src/main/java/com/floney/floney/common/config/RedisConfig.java
- src/main/java/com/floney/floney/common/exception/common/ErrorControllerAdvice.java
- src/main/java/com/floney/floney/common/util/RedisProvider.java
- src/main/java/com/floney/floney/user/infrastructure/PasswordHistoryManagerImpl.java
- src/main/java/com/floney/floney/user/service/PasswordHistoryManager.java
- src/main/java/com/floney/floney/user/service/UserService.java
- src/test/java/com/floney/floney/acceptance/config/IntegrationTestExecutionListener.java
- src/test/java/com/floney/floney/fixture/UserFixture.java
- src/test/java/com/floney/floney/user/service/PasswordHistoryManagerTest.java
- src/test/java/com/floney/floney/user/service/UserServiceTest.java
비밀번호 5번 이상 변경 이후 이전에 사용한 예전 비밀번호 사용 가능
- 레디스를 사용해 회원마다 비밀번호 내역 저장
- `PasswordHistoryManager` 클래스에서 비밀번호 내역 관리 담당
- 관련 테스트 추가
- 인수 & 통합 테스트 시 테스트 마다 레디스 초기화
> #366 feat: 비밀번호 변경 제한 추가

- src/main/java/com/floney/floney/common/exception/common/ErrorControllerAdvice.java
- src/main/java/com/floney/floney/common/exception/common/ErrorType.java
- src/main/java/com/floney/floney/common/exception/user/PasswordNotSameException.java
- src/main/java/com/floney/floney/user/controller/UserController.java
- src/main/java/com/floney/floney/user/dto/request/UpdatePasswordRequest.java
- src/main/java/com/floney/floney/user/service/UserService.java
- src/test/java/com/floney/floney/acceptance/UserAcceptanceTest.java
비밀번호 변경 API 에서 현재 비밀번호를 검증하지 않던 오류를 수정한다.
- 현재 비밀번호를 검증 추가
> #380 fix: 비밀번호 변경 시 현재 비밀번호도 검증

- src/main/java/com/floney/floney/user/entity/User.java
회원 탈퇴시, 가계부 내역이 존재하지 않음 에러 발생으로 인한 이슈 해결
- User inactive() 이전, User 탈퇴 이벤트 시행
> #384 fix : User inactive() 이전, User 탈퇴 이벤트 시행

- .github/CODEOWNERS
- .github/workflows/gradle-build.yml
- src/main/java/com/floney/floney/user/service/UserService.java
- src/test/java/com/floney/floney/user/service/PasswordHistoryManagerTest.java
- src/test/resources/application.yaml
최근 변경한 5개의 비밀번호와 새 비밀번호가 겹치면 안된다는 조건을 삭제했다.
- PasswordHistoryManager 테스트 무효화
- PasswordHistoryManager를 사용하는 코드 삭제
> #403 feat: 비밀번호 변경 조건 삭제

- src/main/java/com/floney/floney/analyze/service/AssetServiceImpl.java
- src/main/java/com/floney/floney/analyze/service/CarryOverServiceImpl.java
- src/main/java/com/floney/floney/book/domain/category/CategoryType.java
- src/main/java/com/floney/floney/book/domain/entity/Asset.java
- src/main/java/com/floney/floney/book/domain/entity/CarryOver.java
- src/main/java/com/floney/floney/book/domain/entity/RepeatBookLine.java
- src/main/java/com/floney/floney/book/repository/AssetJdbcRepository.java
- src/main/java/com/floney/floney/book/repository/CarryOverJdbcRepository.java
- src/main/java/com/floney/floney/user/dto/security/CustomUserDetails.java
- src/test/java/com/floney/floney/book/domain/entity/CarryOverTest.java
- src/test/java/com/floney/floney/book/service/AssetServiceTest.java
- src/test/java/com/floney/floney/book/service/CarryOverServiceTest.java
반복 내역 성능 개선
**_EVERYDAY 로 가계부 내역 추가 시, 수치 확인 후 공유 부탁드립니다_**
- 우선 통과 안하는 테스트는 성능 개선 검토 후 통과하게 만들겠습니다
- 자산, 이월 설정 수치 잘 업데이트 되는거 확인했습니다.
- yml에서 mysql에 `?&rewriteBatchedStatements=true` 설정 해주셔야합니다 
ex. `url: jdbc:mysql://localhost:3306/floney_local?&rewriteBatchedStatements=true`
- dev,prod는 제가 `?&rewriteBatchedStatements=true` 해놨습니다
- 작디 작은 램 부족도 문제인것 같습니다
> #409 fix: 반복 내역 성능 개선

- src/main/java/com/floney/floney/book/repository/analyze/BudgetCustomRepositoryImpl.java
가계부 초기화 후 에산이 초기화 되지 않았음
- DB에서 초기화는 정상 작동
- 조회 할 떄, ACTIVE만 조회하는 조건이 누락 돼, 해당 부분 추가함
> #431 fix : 예산 조회 시, ACTIVE만 조회 조건 추가

- src/main/java/com/floney/floney/book/controller/FavoriteController.java
- src/main/java/com/floney/floney/book/domain/entity/Book.java
- src/main/java/com/floney/floney/book/domain/entity/BookLine.java
- src/main/java/com/floney/floney/book/domain/favorite/Favorite.java
- src/main/java/com/floney/floney/book/dto/request/FavoriteCreateRequest.java
- src/main/java/com/floney/floney/book/dto/response/FavoriteResponse.java
- src/main/java/com/floney/floney/book/repository/favorite/FavoriteRepository.java
- src/main/java/com/floney/floney/book/service/FavoriteService.java
- src/main/java/com/floney/floney/book/service/FavoriteServiceImpl.java
- src/main/java/com/floney/floney/common/exception/book/FavoriteSizeInvalidException.java
- src/main/java/com/floney/floney/common/exception/book/NotFoundBookUserException.java
- src/main/java/com/floney/floney/common/exception/common/ErrorControllerAdvice.java
- src/main/java/com/floney/floney/common/exception/common/ErrorType.java
- src/main/resources/db/migration/mysql/V16__add_favorite.sql
- src/test/java/com/floney/floney/acceptance/FavoriteAcceptanceTest.java
- src/test/java/com/floney/floney/acceptance/fixture/FavoriteApiFixture.java
- src/test/resources/clear.sql
즐겨찾기 추가 API 구현
- 가계부 당 즐겨찾기 개수 10개 제한 구현
- 가계부원이 아닌 사용자가 즐겨찾기 추가 요청 시 제한 구현
- 관련 인수 테스트 추가
> #439 feat: 즐겨찾기 추가 구현

- src/main/java/com/floney/floney/book/domain/category/entity/Category.java
- src/main/java/com/floney/floney/book/domain/entity/Book.java
- src/main/java/com/floney/floney/book/repository/favorite/FavoriteRepository.java
- src/main/java/com/floney/floney/book/service/FavoriteServiceImpl.java
- src/main/java/com/floney/floney/common/exception/book/FavoriteSizeInvalidException.java
- src/test/java/com/floney/floney/acceptance/FavoriteAcceptanceTest.java
즐겨찾기 개수 제한을 카테고리 당 5개로 수정했다.
- 카테고리 추가 시 유효성 검증 수정
- 관련 테스트 수정
> #468 feat: 즐겨찾기 개수 제한을 카테고리 당 5개로 수정

- src/main/java/com/floney/floney/user/entity/User.java
- src/main/java/com/floney/floney/user/service/UserService.java
임시 비밀번호 길이를 8자로 수정했다.
- 임시 비밀번호 길이를 8자로 수정
> #470 feat: 임시 비밀번호 길이 수정

- src/main/java/com/floney/floney/book/service/BookLineServiceImpl.java
- src/test/java/com/floney/floney/acceptance/BookAcceptanceTest.java
반복 내역 -> 주말 날짜 선택 후 
매주 매달 선택 시 일자 미 조정 되도록 수정
- 평일로 반복 주기 선택시에만 조정되도록 수정
> fix: 반복 내역 주말 날짜 선택 후 평일에만 날짜 조정되도록 수정 

- .github/CODEOWNERS
- src/main/java/com/floney/floney/book/service/BookServiceImpl.java
- src/main/java/com/floney/floney/settlement/dto/response/SettlementResponse.java
- src/main/java/com/floney/floney/settlement/repository/SettlementUserCustomRepository.java
- src/main/java/com/floney/floney/settlement/repository/SettlementUserCustomRepositoryImpl.java
- src/main/java/com/floney/floney/settlement/repository/SettlementUserRepository.java
- src/main/java/com/floney/floney/settlement/service/SettlementService.java
정산 세부 내역 조회 시, 비활성화(탈퇴 혹은 가계부 나가기) 유저에 대해 알맞은 응답값을 내려주도록 수정한다.
- 가계부 나가기 API 에서 빠진 SettlementUser 삭제 로직 추가
- 정산 세부 조회 API 에서 응답값 '알수없음' 처리
1. DB 데이터 삭제 이벤트에서 SettlementUser 삭제는 제외합니다. (논리 삭제된 데이터까지 조회가 필요하기 때문)
> #487 fix: 정산 세부 내역 조회 시, 비활성화 유저 처리

- src/main/java/com/floney/floney/book/repository/BookUserRepositoryImpl.java
한 줄 개요
- 마이페이지 조회 시 inactive인 유저까지 집계되는 현상
> hotfix : 마이페이지 유저 조회 시, active인 bookUser만 집계

- src/main/java/com/floney/floney/settlement/dto/response/SettlementResponse.java
가계부에서 나간 유저도 정산 시 '알수없음' 으로 처리했습니다.
> #503 fix: 가계부 나간 유저도 알수없음 처리
